name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: python model/train_model.py

      - name: Test prediction
        run: python app/predict.py

      - name: Build Docker image
        run: docker build -t ml-devops-app .

      # Optional: Push to DockerHub or GHCR
      # Add DockerHub secrets to repo: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
      # - name: Login to DockerHub
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #
      # - name: Push Docker image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-devops-app

